INSERT INTO product (id, name, description, price, product_category_id, product_image_id) VALUES
(1,'Angel Wings Harness','The purrrfect accessory to take your kitty to the next level.',10,4,1),
(2,'Deluxe Carry Bag Orange','Backpack-style carry bag with dome.',20,4,2),
(3,'KittyLove Apron Red','Puff-look apron to protect against dinner time oopsies.',15,4,3),
(4,'Outta Space Dome Carry Bag Yellow','Dome-style re-inforced plastic carry bag.',30,4,4),
(5,'McMeowful Soft Bow Collar Baby Pink','Hypo-allergenic bow with ultrasoft-style security clip for extra comfort.',40,4,5),
(6,'Jumper Grandad-style Grey','Grandad-style jumper from soft merino wool with button-style clips.',5,1,6),
(7,'PartyTime Soldier Outfit Khaki','Party-style soldier outfit, one size fits all.',100,5,7),
(8,'PartyTime Sailor Outfit Small','Party-style sailor outfit, size small.',70,5,8),
(9,'Angel Wings','The purrrfect accessory to take your kitty to the next level.',10,4,16),
(10,'Deluxe Carry Bag Red','Backpack-style carry bag with dome.',20,4,9),
(11,'KittyLove Apron Orange','Puff-look apron to protect against dinner time oopsies.',15,4,10),
(12,'Outta Space Dome Carry Bag Green','Dome-style re-inforced plastic carry bag.',30,4,11),
(13,'McMeowful Soft Bow Collar Baby Purple','Hypo-allergenic bow with ultrasoft-style security clip for extra comfort.',40,4,12),
(14,'Jumper Grandad-style Black','Grandad-style jumper from soft merino wool with button-style clips.',5,1,14),
(15,'PartyTime Soldier Outfit Red','Party-style soldier outfit, one size fits all.',100,5,15),
(16,'PartyTime Sailor Outfit Medium','Party-style sailor outfit, size medium.',70,5,7),
(17,'McMeowful Soft Bow Collar Baby Blue','Hypo-allergenic bow with ultrasoft-style security clip for extra comfort.',40,4,17),
(18,'Jumper Grandad-style Blue','Grandad-style jumper from soft merino wool with button-style clips.',5,1,18),
(19,'PartyTime Soldier Outfit Pink','Party-style soldier outfit, one size fits all.',100,5,20),
(20,'PartyTime Sailor Outfit Large','Party-style sailor outfit, size large.',70,5,19),
(21,'Angel Wings Harness Green','The purrrfect accessory to take your kitty to the next level.',10,4,21),
(22,'Deluxe Carry Bag Blue','Backpack-style carry bag with dome.',20,4,22),
(23,'KittyLove Apron Golden Sun','Puff-look apron to protect against dinner time oopsies.',15,4,23),
(24,'Outta Space Dome Carry Bag Grape','Dome-style re-inforced plastic carry bag.',30,4,24),
(25,'McMeowful Soft Bow Collar Tangerine','Hypo-allergenic bow with ultrasoft-style security clip for extra comfort.',40,4,25),
(26,'Jumper Grandad-style Deep Purple','Grandad-style jumper from soft merino wool with button-style clips.',5,1,26),
(27,'PartyTime Soldier Outfit Teal','Party-style soldier outfit, one size fits all.',100,5,27),
(28,'PartyTime Sailor Outfit Gold','Party-style sailor outfit, size small.',70,5,28),
(29,'Angel Wings Ivy','The purrrfect accessory to take your kitty to the next level.',10,4,29),
(30,'Deluxe Carry Bag Magenta Dark','Backpack-style carry bag with dome.',20,4,30),
(31,'KittyLove Apron Hyper Mint','Puff-look apron to protect against dinner time oopsies.',15,4,31),
(32,'Outta Space Dome Carry Bag Sunset','Dome-style re-inforced plastic carry bag.',30,4,32),
(33,'McMeowful Soft Bow Collar Sunburst','Hypo-allergenic bow with ultrasoft-style security clip for extra comfort.',40,4,33),
(34,'Jumper Grandad-style Green','Grandad-style jumper from soft merino wool with button-style clips.',5,1,34),
(35,'PartyTime Soldier Outfit Flame','Party-style soldier outfit, one size fits all.',100,5,35),
(36,'PartyTime Sailor Outfit Blue Scout','Party-style sailor outfit, size medium.',70,5,36),
(37,'McMeowful Soft Bow Collar Peppermint','Hypo-allergenic bow with ultrasoft-style security clip for extra comfort.',40,4,41),
(38,'Jumper Grandad-style Lemonade','Grandad-style jumper from soft merino wool with button-style clips.',5,1,42),
(39,'PartyTime Soldier Outfit Irishman','Party-style soldier outfit, one size fits all.',100,5,43),
(40,'PartyTime Sailor Outfit Baby Blue','Party-style sailor outfit, size large.',70,5,44),
(41,'Angel Wings Harness','The purrrfect accessory to take your kitty to the next level.',10,4,37),
(42,'Deluxe Carry Bag Ivy','Backpack-style carry bag with dome.',20,4,38),
(43,'KittyLove Apron Royal Blue','Puff-look apron to protect against dinner time oopsies.',15,4,39),
(44,'Outta Space Dome Carry Bag Dusty Pink','Dome-style re-inforced plastic carry bag.',30,4,40),
(45,'McMeowful Soft Bow Collar Valentines','Hypo-allergenic bow with ultrasoft-style security clip for extra comfort.',40,4,45),
(46,'Jumper Grandad-style Candyfloss','Grandad-style jumper from soft merino wool with button-style clips.',5,1,46),
(47,'PartyTime Soldier Outfit Light Blue','Party-style soldier outfit, one size fits all.',100,5,47),
(48,'PartyTime Sailor Outfit Electric Lime','Party-style sailor outfit, size small.',70,5,48),
(49,'Angel Wings','The purrrfect accessory to take your kitty to the next level.',10,4,49),
(50,'PartyTime Sailor Outfit Large','Party-style sailor outfit, size Adjustable.',70,5,8),
(51,'PartyTime Sailor Outfit Large','Party-style sailor outfit, Light Yellow.',70,5,55),
(52,'Angel Wings Harness Brown','The purrrfect accessory to take your kitty to the next level.',10,4,49),
(53,'Deluxe Carry Bag Crimson','Backpack-style carry bag with dome.',20,4,50),
(54,'KittyLove Apron Neutrals','Puff-look apron to protect against dinner time oopsies.',15,4,51),
(55,'Outta Space Dome Carry Bag Fireball','Dome-style re-inforced plastic carry bag.',30,4,52),
(56,'McMeowful Soft Bow Collar Dark Yellow Green','Hypo-allergenic bow with ultrasoft-style security clip for extra comfort.',40,4,53),
(57,'Jumper Grandad-style Coral','Grandad-style jumper from soft merino wool with button-style clips.',5,1,54),
(58,'PartyTime Soldier Outfit Khaki','Party-style soldier outfit, one size fits all.',100,5,7),
(59,'PartyTime Sailor Outfit Light Red','Party-style sailor outfit, size small.',70,5,56),
(60,'Angel Wings','The purrrfect accessory to take your kitty to the next level.',10,4,57),
(61,'Angel Wings Harness','The purrrfect accessory to take your kitty to the next level.',10,4,58),
(62,'Deluxe Carry Bag Poison Stripe Red','Backpack-style carry bag with dome.',20,4,59),
(63,'KittyLove Apron Textured Green','Puff-look apron to protect against dinner time oopsies.',15,4,60),
(64,'Outta Space Dome Carry Bag Radioactive','Dome-style re-inforced plastic carry bag.',30,4,61),
(65,'McMeowful Soft Bow Collar Glowing Teal','Hypo-allergenic bow with ultrasoft-style security clip for extra comfort.',40,4,62),
(66,'Jumper Grandad-style Light Orange','Grandad-style jumper from soft merino wool with button-style clips.',5,1,63),
(67,'PartyTime Soldier Outfit Pink Denim','Party-style soldier outfit, one size fits all.',100,5,64),
(68,'PartyTime Sailor Outfit Light Orange','Party-style sailor outfit, size small.',70,5,65),
(69,'Angel Wings Green Glow','The purrrfect accessory to take your kitty to the next level.',10,4,66),
(70,'Deluxe Carry Bag Green Stripe','Backpack-style carry bag with dome.',20,4,67),
(71,'KittyLove Apron Red Leather','Puff-look apron to protect against dinner time oopsies.',15,4,68),
(72,'Outta Space Dome Carry Bag Pink Glow','Dome-style re-inforced plastic carry bag.',30,4,69),
(73,'McMeowful Soft Bow Collar Purple Glow','Hypo-allergenic bow with ultrasoft-style security clip for extra comfort.',40,4,70),
(74,'Jumper Grandad-style Light Lime','Grandad-style jumper from soft merino wool with button-style clips.',5,1,71),
(75,'PartyTime Soldier Outfit Yellow Stripe','Party-style soldier outfit, one size fits all.',100,5,72),
(76,'PartyTime Sailor Outfit Orange Purple Glow','Party-style sailor outfit, size medium.',70,5,73),
(77,'Angel Wings Blue Glow','The purrrfect accessory to take your kitty to the next level.',10,4,74),
(78,'Deluxe Carry Bag Grape Stripe','Backpack-style carry bag with dome.',20,4,75),
(79,'KittyLove Apron Pool Blue Leather','Puff-look apron to protect against dinner time oopsies.',15,4,76),
(80,'Outta Space Dome Carry Bag Blue Glow','Dome-style re-inforced plastic carry bag.',30,4,77),
(81,'McMeowful Soft Bow Collar Blue Glow','Hypo-allergenic bow with ultrasoft-style security clip for extra comfort.',40,4,78),
(82,'Jumper Grandad-style Purple Aura','Grandad-style jumper from soft merino wool with button-style clips.',5,1,79),
(83,'PartyTime Soldier Outfit Carrot Stripe','Party-style soldier outfit, one size fits all.',100,5,80),
(84,'PartyTime Sailor Outfit Fire Tinge','Party-style sailor outfit, size medium.',70,5,81),
(85,'Angel Wings Valentine Glow','The purrrfect accessory to take your kitty to the next level.',10,4,82),
(86,'Deluxe Carry Bag Blue Stripe','Backpack-style carry bag with dome.',20,4,83),
(87,'KittyLove Apron Pink Leather','Puff-look apron to protect against dinner time oopsies.',15,4,84),
(88,'Outta Space Dome Carry Bag Yellow Glow','Dome-style re-inforced plastic carry bag.',30,4,85),
(89,'McMeowful Soft Bow Collar Blue with Blue Glow','Hypo-allergenic bow with ultrasoft-style security clip for extra comfort.',40,4,86),
(90,'Jumper Grandad-style Tangerine Aura','Grandad-style jumper from soft merino wool with button-style clips.',5,1,87),
(91,'PartyTime Soldier Outfit Blue Stripe','Party-style soldier outfit, one size fits all.',100,5,88),
(92,'PartyTime Sailor Outfit Candy Vibe','Party-style sailor outfit, size medium.',70,5,89),
(93,'Angel Wings Sunrise Victory','The purrrfect accessory to take your kitty to the next level.',10,4,90),
(94,'Deluxe Carry Bag Mustard Stripe','Backpack-style carry bag with dome.',20,4,91),
(95,'KittyLove Apron Purple Leather','Puff-look apron to protect against dinner time oopsies.',15,4,92),
(96,'Outta Space Dome Carry Bag Red-orange Glow','Dome-style re-inforced plastic carry bag.',30,4,93),
(97,'McMeowful Soft Bow Collar Mustard with Mustard Glow','Hypo-allergenic bow with ultrasoft-style security clip for extra comfort.',40,4,94),
(98,'Jumper Grandad-style Peppermint Glow','Grandad-style jumper from soft merino wool with button-style clips.',5,1,95),
(99,'PartyTime Soldier Outfit Capsicum','Party-style soldier outfit, one size fits all.',100,5,96),
(100,'PartyTime Sailor Outfit Plum Glow','Party-style sailor outfit, size medium.',70,5,97);
